//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bus_company.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Money { get; set; }
        public Nullable<int> IdTimeTable { get; set; }
        public string IdUser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Timetable Timetable { get; set; }
    }
}
